import { supabase } from '@/lib/supabase'
import Link from 'next/link'

interface Props {
  params: Promise<{ reference: string; chargeId: string }>
}

const POUND = String.fromCharCode(0xA3)
const DASH  = String.fromCharCode(0x2014)

function fmt(v: number | string | null | undefined): string {
  if (v == null || v === '') return DASH
  const n = typeof v === 'string' ? parseFloat(v) : v
  if (isNaN(n)) return DASH
  return POUND + n.toLocaleString('en-GB', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
}

function fmtDate(s: string | null | undefined): string {
  if (!s) return DASH
  return new Date(s).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
}

function formatUnit(ref: string | null | undefined): string {
  if (!ref) return DASH
  const parts = ref.trim().split('-')
  return 'Unit ' + parts[parts.length - 1]
}

const STATUS_BADGE: Record<string, string> = {
  DRAFT:       'bg-slate-100 text-slate-600',
  ISSUED:      'bg-blue-100 text-blue-700',
  PAID:        'bg-emerald-100 text-emerald-700',
  PART_PAID:   'bg-amber-100 text-amber-800',
  OVERDUE:     'bg-red-100 text-red-700',
  WRITTEN_OFF: 'bg-gray-100 text-gray-500',
  CREDITED:    'bg-purple-100 text-purple-700',
}

function statusLabel(s: string): string {
  return s.charAt(0) + s.slice(1).toLowerCase().replace('_', ' ')
}

function DetailRow({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <dt className="text-xs text-slate-400 uppercase tracking-wide mb-0.5">{label}</dt>
      <dd className="text-sm font-medium text-slate-900">{value}</dd>
    </div>
  )
}

export default async function ChargeDetailPage({ params }: Props) {
  const { reference, chargeId } = await params

  const { data: charge } = await supabase
    .from('v_charge_ledger')
    .select('*')
    .eq('charge_id', chargeId)
    .single()

  if (!charge) {
    return (
      <div className="p-8">
        <p className="text-red-500 mb-4">Charge not found.</p>
        <Link href={`/assets/${reference}/billing`} className="text-blue-600 hover:underline text-sm">
          {String.fromCharCode(0x2190)} Back to billing
        </Link>
      </div>
    )
  }

  const canPay = ['ISSUED', 'OVERDUE', 'PART_PAID'].includes(charge.status)
  const vatPct = parseFloat(charge.vat_rate ?? '0') * 100
  const vatLabel = vatPct > 0 ? `VAT (${vatPct.toFixed(0)}%)` : 'VAT (0%)'

  return (
    <div className="p-6 md:p-10 max-w-3xl">
      {/* Breadcrumb */}
      <nav className="text-sm text-slate-400 mb-6 flex items-center gap-2 flex-wrap">
        <Link href="/" className="hover:text-slate-600">Dashboard</Link>
        <span>/</span>
        <Link href={`/assets/${reference}`} className="hover:text-slate-600">{charge.asset_name}</Link>
        <span>/</span>
        <Link href={`/assets/${reference}/billing`} className="hover:text-slate-600">Billing</Link>
        <span>/</span>
        <span className="text-slate-700 font-medium">{charge.charge_label}</span>
      </nav>

      {/* Header */}
      <div className="flex items-start justify-between mb-8 gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">{charge.tenant_name}</h1>
          <p className="text-slate-500 mt-1">
            {formatUnit(charge.unit_reference)}
            <span className="text-slate-400 text-xs ml-1">({charge.unit_reference})</span>
            <span className="mx-2 text-slate-300">{DASH}</span>
            <span className="text-slate-500">{charge.asset_name}</span>
          </p>
        </div>
        <span className={`mt-1 inline-flex items-center px-3 py-1 rounded-full text-xs font-semibold ${STATUS_BADGE[charge.status] ?? 'bg-gray-100 text-gray-600'}`}>
          {statusLabel(charge.status)}
        </span>
      </div>

      {/* Financial breakdown */}
      <div className="bg-white border border-slate-200 rounded-xl p-6 mb-6">
        <h2 className="text-sm font-semibold text-slate-700 uppercase tracking-wide mb-5">Charge Details</h2>
        <dl className="grid grid-cols-2 gap-x-10 gap-y-5">
          <DetailRow label="Description"    value={charge.charge_label ?? DASH} />
          <DetailRow label="Lease Reference" value={charge.lease_reference ?? DASH} />
          <DetailRow label="Period Start"   value={fmtDate(charge.period_start)} />
          <DetailRow label="Period End"     value={fmtDate(charge.period_end)} />
          <DetailRow label="Due Date"       value={fmtDate(charge.due_date)} />
          <DetailRow label="Generated By"   value={charge.generated_by ?? DASH} />
          <DetailRow label="Net Amount"     value={fmt(charge.net_amount)} />
          <DetailRow label={vatLabel}       value={fmt(charge.vat_amount)} />
        </dl>

        {/* Gross highlight */}
        <div className="mt-6 pt-5 border-t border-slate-100 flex justify-between items-center">
          <span className="text-sm font-semibold text-slate-700">Gross Amount</span>
          <span className="text-2xl font-bold text-slate-900">{fmt(charge.gross_amount)}</span>
        </div>
      </div>

      {/* Payment info (if paid/part paid) */}
      {charge.payment_amount && (
        <div className="bg-emerald-50 border border-emerald-200 rounded-xl p-5 mb-6">
          <h2 className="text-sm font-semibold text-emerald-800 uppercase tracking-wide mb-3">Payment Received</h2>
          <div className="flex gap-8">
            <div>
              <p className="text-xs text-emerald-600 mb-0.5">Amount</p>
              <p className="text-lg font-bold text-emerald-800">{fmt(charge.payment_amount)}</p>
            </div>
            <div>
              <p className="text-xs text-emerald-600 mb-0.5">Date</p>
              <p className="text-lg font-bold text-emerald-800">{fmtDate(charge.payment_date)}</p>
            </div>
            {charge.status === 'PART_PAID' && (
              <div>
                <p className="text-xs text-emerald-600 mb-0.5">Still Outstanding</p>
                <p className="text-lg font-bold text-amber-700">{fmt(charge.outstanding_amount)}</p>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Notes */}
      {charge.notes && (
        <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 mb-6">
          <p className="text-xs font-semibold text-amber-700 uppercase tracking-wide mb-1">Note</p>
          <p className="text-sm text-amber-800">{charge.notes}</p>
        </div>
      )}

      {/* Payment form */}
      <div className="bg-slate-50 border border-slate-200 rounded-xl p-5 text-sm text-slate-600">
        Payments are recorded in the{' '}
        <Link href={`/assets/${reference}/payments`} className="text-blue-600 hover:underline font-medium">Rent Payment Register</Link>
        {' '}or the{' '}
        <Link href={`/assets/${reference}/electric`} className="text-blue-600 hover:underline font-medium">Electric page</Link>
        {' '}so every receipt is allocated consistently.
      </div>

      {/* Back link */}
      <div className="mt-8">
        <Link href={`/assets/${reference}/billing`} className="text-sm text-slate-500 hover:text-slate-800">
          {String.fromCharCode(0x2190)} Back to billing
        </Link>
      </div>
    </div>
  )
}