-- Live public-schema ENUMS / CONSTRAINTS / INDEXES / TRIGGERS - Supabase project jkpftidophjivmaqpkuu - captured 2026-07-04 (pre-remediation snapshot)

-- ENUM TYPES

CREATE TYPE public.apportionment_basis_enum AS ENUM ('FLOOR_AREA', 'EQUAL_SHARE', 'CUSTOM');
CREATE TYPE public.asset_type_enum AS ENUM ('RETAIL_PARK', 'RETAIL', 'OFFICE', 'MIXED_USE', 'INDUSTRIAL', 'OTHER');
CREATE TYPE public.billing_frequency_enum AS ENUM ('MONTHLY', 'QUARTERLY', 'ANNUAL');
CREATE TYPE public.break_clause_party_enum AS ENUM ('LANDLORD', 'TENANT', 'MUTUAL');
CREATE TYPE public.calculation_method_enum AS ENUM ('FIXED', 'METER_BASED', 'APPORTIONED');
CREATE TYPE public.charge_status_enum AS ENUM ('DRAFT', 'APPROVED', 'ISSUED', 'PAID', 'PART_PAID', 'OVERDUE', 'DISPUTED', 'WRITTEN_OFF', 'CREDITED');
CREATE TYPE public.charge_type_enum AS ENUM ('RENT', 'ELECTRIC', 'INSURANCE', 'WATER', 'SERVICE_CHARGE', 'CREDIT', 'OTHER');
CREATE TYPE public.compliance_status_enum AS ENUM ('COMPLIANT', 'DUE_SOON', 'OVERDUE', 'NOT_APPLICABLE');
CREATE TYPE public.compliance_type_enum AS ENUM ('EPC', 'EICR', 'GAS_SAFETY', 'FIRE_RISK', 'ASBESTOS', 'LEGIONELLA', 'HVAC', 'LIFT', 'INSURANCE', 'PAT', 'OTHER');
CREATE TYPE public.deposit_type_enum AS ENUM ('CASH', 'GUARANTEE', 'NONE');
CREATE TYPE public.document_type_enum AS ENUM ('LEASE', 'COMPLIANCE_CERT', 'MAINTENANCE', 'CORRESPONDENCE', 'BILLING', 'INSPECTION', 'OTHER');
CREATE TYPE public.entity_type_enum AS ENUM ('PORTFOLIO', 'ASSET', 'BLOCK', 'UNIT', 'LEASE', 'TENANT', 'CHARGE_RECORD', 'COMPLIANCE_RECORD', 'MAINTENANCE_EVENT', 'SIGNIFICANT_EVENT', 'CONTRACTOR', 'METER', 'DOCUMENT');
CREATE TYPE public.event_category_enum AS ENUM ('FINANCIAL', 'LEASE', 'OPERATIONAL', 'TENANT', 'STRATEGIC', 'COMPLIANCE');
CREATE TYPE public.file_format_enum AS ENUM ('PDF', 'DOCX', 'XLSX', 'JPG', 'OTHER');
CREATE TYPE public.generated_by_enum AS ENUM ('SYSTEM', 'MANUAL');
CREATE TYPE public.incentive_type_enum AS ENUM ('RENT_FREE', 'FIXED_DISCOUNT', 'STEPPED_RENT');
CREATE TYPE public.lease_state_enum AS ENUM ('ACTIVE', 'APPROACHING_REVIEW', 'APPROACHING_EXPIRY', 'PERIODIC', 'TERMINATED');
CREATE TYPE public.lease_type_enum AS ENUM ('FIXED_TERM', 'PERIODIC', 'TENANCY_AT_WILL');
CREATE TYPE public.maintenance_category_enum AS ENUM ('REACTIVE', 'PLANNED', 'COMPLIANCE', 'VOID_WORKS', 'CAPITAL');
CREATE TYPE public.maintenance_priority_enum AS ENUM ('EMERGENCY', 'URGENT', 'ROUTINE', 'PLANNED');
CREATE TYPE public.maintenance_status_enum AS ENUM ('REPORTED', 'QUOTED', 'INSTRUCTED', 'IN_PROGRESS', 'COMPLETE', 'INVOICED');
CREATE TYPE public.meter_type_enum AS ENUM ('ELECTRICITY', 'WATER', 'GAS');
CREATE TYPE public.read_type_enum AS ENUM ('ACTUAL', 'ESTIMATED');
CREATE TYPE public.rent_review_basis_enum AS ENUM ('OPEN_MARKET', 'RPI', 'CPI', 'FIXED_UPLIFT', 'NONE');
CREATE TYPE public.repairing_obligation_enum AS ENUM ('FRI', 'IRI', 'SCHEDULE_OF_CONDITION', 'OTHER');
CREATE TYPE public.tenant_state_enum AS ENUM ('STABLE', 'SLOW_PAYER', 'ARREARS_CONCERN');
CREATE TYPE public.tenant_type_enum AS ENUM ('COMPANY', 'INDIVIDUAL', 'PARTNERSHIP', 'OTHER');
CREATE TYPE public.termination_reason_enum AS ENUM ('EXPIRY', 'SURRENDER', 'BREAK_LANDLORD', 'BREAK_TENANT', 'FORFEITURE');
CREATE TYPE public.unit_state_enum AS ENUM ('OCCUPIED', 'VACANT', 'UNDER_OFFER');
CREATE TYPE public.unit_type_enum AS ENUM ('OFFICE', 'RETAIL', 'WORKSHOP', 'STORAGE', 'OTHER');
CREATE TYPE public.utility_type_enum AS ENUM ('ELECTRICITY', 'WATER', 'GAS');
CREATE TYPE public.vat_treatment_enum AS ENUM ('STANDARD', 'EXEMPT', 'ZERO_RATED', 'OUTSIDE_SCOPE', 'VAT_DEFERRED');

-- CONSTRAINTS

ALTER TABLE public.arrears_actions ADD CONSTRAINT arrears_actions_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES assets(asset_id);
ALTER TABLE public.arrears_actions ADD CONSTRAINT arrears_actions_pkey PRIMARY KEY (action_id);
ALTER TABLE public.arrears_actions ADD CONSTRAINT arrears_actions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id);
ALTER TABLE public.assets ADD CONSTRAINT assets_asset_reference_key UNIQUE (asset_reference);
ALTER TABLE public.assets ADD CONSTRAINT assets_letterhead_template_id_fkey FOREIGN KEY (letterhead_template_id) REFERENCES document_templates(template_id);
ALTER TABLE public.assets ADD CONSTRAINT assets_pkey PRIMARY KEY (asset_id);
ALTER TABLE public.assets ADD CONSTRAINT assets_portfolio_id_fkey FOREIGN KEY (portfolio_id) REFERENCES portfolios(portfolio_id);
ALTER TABLE public.blocks ADD CONSTRAINT blocks_asset_id_block_reference_key UNIQUE (asset_id, block_reference);
ALTER TABLE public.blocks ADD CONSTRAINT blocks_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES assets(asset_id);
ALTER TABLE public.blocks ADD CONSTRAINT blocks_pkey PRIMARY KEY (block_id);
ALTER TABLE public.blocks ADD CONSTRAINT blocks_utility_rate_id_fkey FOREIGN KEY (utility_rate_id) REFERENCES utility_rates(rate_id);
ALTER TABLE public.charge_profiles ADD CONSTRAINT charge_profiles_lease_id_charge_type_key UNIQUE (lease_id, charge_type);
ALTER TABLE public.charge_profiles ADD CONSTRAINT charge_profiles_lease_id_fkey FOREIGN KEY (lease_id) REFERENCES leases(lease_id);
ALTER TABLE public.charge_profiles ADD CONSTRAINT charge_profiles_pkey PRIMARY KEY (profile_id);
ALTER TABLE public.charge_records ADD CONSTRAINT charge_records_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES assets(asset_id);
ALTER TABLE public.charge_records ADD CONSTRAINT charge_records_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(document_id);
ALTER TABLE public.charge_records ADD CONSTRAINT charge_records_lease_id_fkey FOREIGN KEY (lease_id) REFERENCES leases(lease_id);
ALTER TABLE public.charge_records ADD CONSTRAINT charge_records_pkey PRIMARY KEY (charge_id);
ALTER TABLE public.charge_records ADD CONSTRAINT charge_records_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id);
ALTER TABLE public.charge_records ADD CONSTRAINT charge_records_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES units(unit_id);
ALTER TABLE public.charge_records ADD CONSTRAINT issued_requires_date CHECK (((status = ANY (ARRAY['DRAFT'::charge_status_enum, 'APPROVED'::charge_status_enum])) OR (issued_date IS NOT NULL)));
ALTER TABLE public.charge_records ADD CONSTRAINT valid_period CHECK ((period_start <= period_end));
ALTER TABLE public.compliance_records ADD CONSTRAINT compliance_records_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES assets(asset_id);
ALTER TABLE public.compliance_records ADD CONSTRAINT compliance_records_contractor_id_fkey FOREIGN KEY (contractor_id) REFERENCES contractors(contractor_id);
ALTER TABLE public.compliance_records ADD CONSTRAINT compliance_records_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(document_id);
ALTER TABLE public.compliance_records ADD CONSTRAINT compliance_records_pkey PRIMARY KEY (compliance_id);
ALTER TABLE public.compliance_records ADD CONSTRAINT compliance_records_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES units(unit_id);
ALTER TABLE public.contractors ADD CONSTRAINT contractors_pkey PRIMARY KEY (contractor_id);
ALTER TABLE public.document_links ADD CONSTRAINT document_links_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(document_id);
ALTER TABLE public.document_links ADD CONSTRAINT document_links_pkey PRIMARY KEY (document_id, entity_type, entity_id);
ALTER TABLE public.document_templates ADD CONSTRAINT document_templates_pkey PRIMARY KEY (template_id);
ALTER TABLE public.document_templates ADD CONSTRAINT document_templates_template_reference_key UNIQUE (template_reference);
ALTER TABLE public.documents ADD CONSTRAINT documents_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES assets(asset_id);
ALTER TABLE public.documents ADD CONSTRAINT documents_charge_id_fkey FOREIGN KEY (charge_id) REFERENCES charge_records(charge_id);
ALTER TABLE public.documents ADD CONSTRAINT documents_compliance_id_fkey FOREIGN KEY (compliance_id) REFERENCES compliance_records(compliance_id);
ALTER TABLE public.documents ADD CONSTRAINT documents_lease_id_fkey FOREIGN KEY (lease_id) REFERENCES leases(lease_id);
ALTER TABLE public.documents ADD CONSTRAINT documents_maintenance_id_fkey FOREIGN KEY (maintenance_id) REFERENCES maintenance_events(maintenance_id);
ALTER TABLE public.documents ADD CONSTRAINT documents_pkey PRIMARY KEY (document_id);
ALTER TABLE public.documents ADD CONSTRAINT documents_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id);
ALTER TABLE public.documents ADD CONSTRAINT documents_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES units(unit_id);
ALTER TABLE public.event_links ADD CONSTRAINT event_links_event_id_fkey FOREIGN KEY (event_id) REFERENCES significant_events(event_id);
ALTER TABLE public.event_links ADD CONSTRAINT event_links_pkey PRIMARY KEY (event_id, entity_type, entity_id);
ALTER TABLE public.issuing_entities ADD CONSTRAINT issuing_entities_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES assets(asset_id);
ALTER TABLE public.issuing_entities ADD CONSTRAINT issuing_entities_asset_id_key UNIQUE (asset_id);
ALTER TABLE public.issuing_entities ADD CONSTRAINT issuing_entities_dispatch_channel_check CHECK ((dispatch_channel = ANY (ARRAY['EMAIL'::text, 'WHATSAPP'::text, 'BOTH'::text])));
ALTER TABLE public.issuing_entities ADD CONSTRAINT issuing_entities_pkey PRIMARY KEY (entity_id);
ALTER TABLE public.lease_units ADD CONSTRAINT lease_units_lease_id_fkey FOREIGN KEY (lease_id) REFERENCES leases(lease_id);
ALTER TABLE public.lease_units ADD CONSTRAINT lease_units_pkey PRIMARY KEY (lease_id, unit_id);
ALTER TABLE public.lease_units ADD CONSTRAINT lease_units_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES units(unit_id);
ALTER TABLE public.leases ADD CONSTRAINT leases_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES assets(asset_id);
ALTER TABLE public.leases ADD CONSTRAINT leases_billing_day_check CHECK (((billing_day >= 1) AND (billing_day <= 28)));
ALTER TABLE public.leases ADD CONSTRAINT leases_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(document_id);
ALTER TABLE public.leases ADD CONSTRAINT leases_lease_reference_key UNIQUE (lease_reference);
ALTER TABLE public.leases ADD CONSTRAINT leases_pkey PRIMARY KEY (lease_id);
ALTER TABLE public.leases ADD CONSTRAINT leases_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id);
ALTER TABLE public.leases ADD CONSTRAINT terminated_requires_date CHECK (((lease_state <> 'TERMINATED'::lease_state_enum) OR (termination_date IS NOT NULL)));
ALTER TABLE public.maintenance_events ADD CONSTRAINT maintenance_events_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES assets(asset_id);
ALTER TABLE public.maintenance_events ADD CONSTRAINT maintenance_events_contractor_id_fkey FOREIGN KEY (contractor_id) REFERENCES contractors(contractor_id);
ALTER TABLE public.maintenance_events ADD CONSTRAINT maintenance_events_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(document_id);
ALTER TABLE public.maintenance_events ADD CONSTRAINT maintenance_events_pkey PRIMARY KEY (maintenance_id);
ALTER TABLE public.maintenance_events ADD CONSTRAINT maintenance_events_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id);
ALTER TABLE public.maintenance_events ADD CONSTRAINT maintenance_events_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES units(unit_id);
ALTER TABLE public.maintenance_events ADD CONSTRAINT rechargeable_requires_tenant CHECK (((rechargeable_to_tenant = false) OR (tenant_id IS NOT NULL)));
ALTER TABLE public.meter_reads ADD CONSTRAINT meter_reads_charge_id_fkey FOREIGN KEY (charge_id) REFERENCES charge_records(charge_id);
ALTER TABLE public.meter_reads ADD CONSTRAINT meter_reads_meter_id_fkey FOREIGN KEY (meter_id) REFERENCES meters(meter_id);
ALTER TABLE public.meter_reads ADD CONSTRAINT meter_reads_pkey PRIMARY KEY (read_id);
ALTER TABLE public.meters ADD CONSTRAINT meters_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES assets(asset_id);
ALTER TABLE public.meters ADD CONSTRAINT meters_block_id_fkey FOREIGN KEY (block_id) REFERENCES blocks(block_id);
ALTER TABLE public.meters ADD CONSTRAINT meters_meter_reference_key UNIQUE (meter_reference);
ALTER TABLE public.meters ADD CONSTRAINT meters_pkey PRIMARY KEY (meter_id);
ALTER TABLE public.meters ADD CONSTRAINT meters_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES units(unit_id);
ALTER TABLE public.payment_allocations ADD CONSTRAINT payment_allocations_allocated_amount_check CHECK ((allocated_amount > (0)::numeric));
ALTER TABLE public.payment_allocations ADD CONSTRAINT payment_allocations_charge_id_fkey FOREIGN KEY (charge_id) REFERENCES charge_records(charge_id);
ALTER TABLE public.payment_allocations ADD CONSTRAINT payment_allocations_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES payments(payment_id) ON DELETE CASCADE;
ALTER TABLE public.payment_allocations ADD CONSTRAINT payment_allocations_pkey PRIMARY KEY (allocation_id);
ALTER TABLE public.payments ADD CONSTRAINT payments_amount_check CHECK ((amount > (0)::numeric));
ALTER TABLE public.payments ADD CONSTRAINT payments_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES assets(asset_id);
ALTER TABLE public.payments ADD CONSTRAINT payments_method_check CHECK ((method = ANY (ARRAY['BANK_TRANSFER'::text, 'STANDING_ORDER'::text, 'CASH'::text, 'CHEQUE'::text, 'CARD'::text, 'OTHER'::text])));
ALTER TABLE public.payments ADD CONSTRAINT payments_pkey PRIMARY KEY (payment_id);
ALTER TABLE public.payments ADD CONSTRAINT payments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id);
ALTER TABLE public.portfolios ADD CONSTRAINT portfolios_pkey PRIMARY KEY (portfolio_id);
ALTER TABLE public.portfolios ADD CONSTRAINT portfolios_portfolio_reference_key UNIQUE (portfolio_reference);
ALTER TABLE public.rent_incentives ADD CONSTRAINT rent_incentives_lease_id_fkey FOREIGN KEY (lease_id) REFERENCES leases(lease_id);
ALTER TABLE public.rent_incentives ADD CONSTRAINT rent_incentives_pkey PRIMARY KEY (incentive_id);
ALTER TABLE public.significant_events ADD CONSTRAINT significant_events_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES assets(asset_id);
ALTER TABLE public.significant_events ADD CONSTRAINT significant_events_contractor_id_fkey FOREIGN KEY (contractor_id) REFERENCES contractors(contractor_id);
ALTER TABLE public.significant_events ADD CONSTRAINT significant_events_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(document_id);
ALTER TABLE public.significant_events ADD CONSTRAINT significant_events_lease_id_fkey FOREIGN KEY (lease_id) REFERENCES leases(lease_id);
ALTER TABLE public.significant_events ADD CONSTRAINT significant_events_pkey PRIMARY KEY (event_id);
ALTER TABLE public.significant_events ADD CONSTRAINT significant_events_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id);
ALTER TABLE public.significant_events ADD CONSTRAINT significant_events_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES units(unit_id);
ALTER TABLE public.supplier_bills ADD CONSTRAINT supplier_bills_asset_id_block_name_bill_month_key UNIQUE (asset_id, block_name, bill_month);
ALTER TABLE public.supplier_bills ADD CONSTRAINT supplier_bills_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES assets(asset_id);
ALTER TABLE public.supplier_bills ADD CONSTRAINT supplier_bills_pkey PRIMARY KEY (bill_id);
ALTER TABLE public.tenant_activity ADD CONSTRAINT tenant_activity_activity_type_check CHECK ((activity_type = ANY (ARRAY['CALL'::text, 'EMAIL'::text, 'RENT_DEMAND'::text, 'COMPLAINT'::text, 'MAINTENANCE'::text, 'SITE_VISIT'::text, 'RENT_REVIEW'::text, 'PAYMENT'::text, 'SYSTEM'::text, 'OTHER'::text])));
ALTER TABLE public.tenant_activity ADD CONSTRAINT tenant_activity_lease_id_fkey FOREIGN KEY (lease_id) REFERENCES leases(lease_id);
ALTER TABLE public.tenant_activity ADD CONSTRAINT tenant_activity_pkey PRIMARY KEY (activity_id);
ALTER TABLE public.tenant_activity ADD CONSTRAINT tenant_activity_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id);
ALTER TABLE public.tenants ADD CONSTRAINT tenants_pkey PRIMARY KEY (tenant_id);
ALTER TABLE public.units ADD CONSTRAINT units_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES assets(asset_id);
ALTER TABLE public.units ADD CONSTRAINT units_block_id_fkey FOREIGN KEY (block_id) REFERENCES blocks(block_id);
ALTER TABLE public.units ADD CONSTRAINT units_merged_into_unit_id_fkey FOREIGN KEY (merged_into_unit_id) REFERENCES units(unit_id);
ALTER TABLE public.units ADD CONSTRAINT units_meter_id_fkey FOREIGN KEY (meter_id) REFERENCES meters(meter_id);
ALTER TABLE public.units ADD CONSTRAINT units_pkey PRIMARY KEY (unit_id);
ALTER TABLE public.units ADD CONSTRAINT units_split_from_unit_id_fkey FOREIGN KEY (split_from_unit_id) REFERENCES units(unit_id);
ALTER TABLE public.units ADD CONSTRAINT units_unit_reference_key UNIQUE (unit_reference);
ALTER TABLE public.utility_rates ADD CONSTRAINT unique_current_rate UNIQUE NULLS NOT DISTINCT (asset_id, block_id, utility_type, effective_to) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.utility_rates ADD CONSTRAINT utility_rates_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES assets(asset_id);
ALTER TABLE public.utility_rates ADD CONSTRAINT utility_rates_block_id_fkey FOREIGN KEY (block_id) REFERENCES blocks(block_id);
ALTER TABLE public.utility_rates ADD CONSTRAINT utility_rates_pkey PRIMARY KEY (rate_id);
ALTER TABLE public.utility_rates ADD CONSTRAINT utility_rates_rate_reference_key UNIQUE (rate_reference);
ALTER TABLE public.vat_config ADD CONSTRAINT vat_config_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES assets(asset_id) ON DELETE CASCADE;
ALTER TABLE public.vat_config ADD CONSTRAINT vat_config_pkey PRIMARY KEY (asset_id);

-- INDEXES

CREATE UNIQUE INDEX arrears_actions_pkey ON public.arrears_actions USING btree (action_id);
CREATE UNIQUE INDEX assets_asset_reference_key ON public.assets USING btree (asset_reference);
CREATE UNIQUE INDEX assets_pkey ON public.assets USING btree (asset_id);
CREATE UNIQUE INDEX blocks_asset_id_block_reference_key ON public.blocks USING btree (asset_id, block_reference);
CREATE UNIQUE INDEX blocks_pkey ON public.blocks USING btree (block_id);
CREATE UNIQUE INDEX charge_profiles_lease_id_charge_type_key ON public.charge_profiles USING btree (lease_id, charge_type);
CREATE UNIQUE INDEX charge_profiles_pkey ON public.charge_profiles USING btree (profile_id);
CREATE UNIQUE INDEX charge_records_pkey ON public.charge_records USING btree (charge_id);
CREATE UNIQUE INDEX compliance_records_pkey ON public.compliance_records USING btree (compliance_id);
CREATE UNIQUE INDEX contractors_pkey ON public.contractors USING btree (contractor_id);
CREATE UNIQUE INDEX document_links_pkey ON public.document_links USING btree (document_id, entity_type, entity_id);
CREATE UNIQUE INDEX document_templates_pkey ON public.document_templates USING btree (template_id);
CREATE UNIQUE INDEX document_templates_template_reference_key ON public.document_templates USING btree (template_reference);
CREATE UNIQUE INDEX documents_pkey ON public.documents USING btree (document_id);
CREATE UNIQUE INDEX event_links_pkey ON public.event_links USING btree (event_id, entity_type, entity_id);
CREATE INDEX idx_activity_tenant ON public.tenant_activity USING btree (tenant_id, activity_at DESC);
CREATE INDEX idx_alloc_charge ON public.payment_allocations USING btree (charge_id);
CREATE INDEX idx_alloc_payment ON public.payment_allocations USING btree (payment_id);
CREATE INDEX idx_arrears_actions_tenant ON public.arrears_actions USING btree (asset_id, tenant_id, action_date DESC);
CREATE INDEX idx_assets_portfolio_id ON public.assets USING btree (portfolio_id);
CREATE INDEX idx_blocks_asset_id ON public.blocks USING btree (asset_id);
CREATE INDEX idx_charge_profiles_lease_id ON public.charge_profiles USING btree (lease_id);
CREATE INDEX idx_charge_records_asset_id ON public.charge_records USING btree (asset_id);
CREATE INDEX idx_charge_records_due_date ON public.charge_records USING btree (due_date);
CREATE INDEX idx_charge_records_lease_id ON public.charge_records USING btree (lease_id);
CREATE INDEX idx_charge_records_status ON public.charge_records USING btree (status);
CREATE INDEX idx_charge_records_tenant_id ON public.charge_records USING btree (tenant_id);
CREATE INDEX idx_charge_records_unit_id ON public.charge_records USING btree (unit_id);
CREATE INDEX idx_compliance_asset_id ON public.compliance_records USING btree (asset_id);
CREATE INDEX idx_compliance_expiry ON public.compliance_records USING btree (expiry_date) WHERE (active = true);
CREATE INDEX idx_compliance_status ON public.compliance_records USING btree (status);
CREATE INDEX idx_document_links_entity ON public.document_links USING btree (entity_type, entity_id);
CREATE INDEX idx_documents_asset_id ON public.documents USING btree (asset_id);
CREATE INDEX idx_documents_charge_id ON public.documents USING btree (charge_id);
CREATE INDEX idx_documents_lease_id ON public.documents USING btree (lease_id);
CREATE INDEX idx_documents_tenant_id ON public.documents USING btree (tenant_id);
CREATE INDEX idx_event_links_entity ON public.event_links USING btree (entity_type, entity_id);
CREATE INDEX idx_lease_units_lease_id ON public.lease_units USING btree (lease_id);
CREATE INDEX idx_lease_units_unit_id ON public.lease_units USING btree (unit_id);
CREATE INDEX idx_leases_asset_id ON public.leases USING btree (asset_id);
CREATE INDEX idx_leases_break_date ON public.leases USING btree (break_clause_date) WHERE (active = true);
CREATE INDEX idx_leases_expiry_date ON public.leases USING btree (expiry_date) WHERE (active = true);
CREATE INDEX idx_leases_lease_state ON public.leases USING btree (lease_state);
CREATE INDEX idx_leases_review_date ON public.leases USING btree (next_rent_review_date) WHERE (active = true);
CREATE INDEX idx_leases_tenant_id ON public.leases USING btree (tenant_id);
CREATE INDEX idx_maintenance_asset_id ON public.maintenance_events USING btree (asset_id);
CREATE INDEX idx_maintenance_status ON public.maintenance_events USING btree (status);
CREATE INDEX idx_meter_reads_meter_date ON public.meter_reads USING btree (meter_id, read_date DESC);
CREATE INDEX idx_meters_asset_id ON public.meters USING btree (asset_id);
CREATE INDEX idx_payments_asset ON public.payments USING btree (asset_id, payment_date DESC);
CREATE INDEX idx_payments_tenant ON public.payments USING btree (tenant_id);
CREATE INDEX idx_rent_incentives_end_date ON public.rent_incentives USING btree (incentive_end_date) WHERE (active = true);
CREATE INDEX idx_rent_incentives_lease_id ON public.rent_incentives USING btree (lease_id);
CREATE INDEX idx_sig_events_asset_id ON public.significant_events USING btree (asset_id);
CREATE INDEX idx_sig_events_event_date ON public.significant_events USING btree (event_date DESC);
CREATE INDEX idx_sig_events_tenant_id ON public.significant_events USING btree (tenant_id);
CREATE INDEX idx_units_asset_id ON public.units USING btree (asset_id);
CREATE INDEX idx_units_block_id ON public.units USING btree (block_id);
CREATE INDEX idx_units_unit_state ON public.units USING btree (unit_state);
CREATE INDEX idx_utility_rates_asset_id ON public.utility_rates USING btree (asset_id);
CREATE INDEX idx_utility_rates_block_id ON public.utility_rates USING btree (block_id);
CREATE INDEX idx_utility_rates_effective ON public.utility_rates USING btree (asset_id, utility_type, effective_from);
CREATE UNIQUE INDEX issuing_entities_asset_id_key ON public.issuing_entities USING btree (asset_id);
CREATE UNIQUE INDEX issuing_entities_pkey ON public.issuing_entities USING btree (entity_id);
CREATE UNIQUE INDEX lease_units_pkey ON public.lease_units USING btree (lease_id, unit_id);
CREATE UNIQUE INDEX leases_lease_reference_key ON public.leases USING btree (lease_reference);
CREATE UNIQUE INDEX leases_pkey ON public.leases USING btree (lease_id);
CREATE UNIQUE INDEX maintenance_events_pkey ON public.maintenance_events USING btree (maintenance_id);
CREATE UNIQUE INDEX meter_reads_pkey ON public.meter_reads USING btree (read_id);
CREATE UNIQUE INDEX meters_meter_reference_key ON public.meters USING btree (meter_reference);
CREATE UNIQUE INDEX meters_pkey ON public.meters USING btree (meter_id);
CREATE UNIQUE INDEX payment_allocations_pkey ON public.payment_allocations USING btree (allocation_id);
CREATE UNIQUE INDEX payments_pkey ON public.payments USING btree (payment_id);
CREATE UNIQUE INDEX portfolios_pkey ON public.portfolios USING btree (portfolio_id);
CREATE UNIQUE INDEX portfolios_portfolio_reference_key ON public.portfolios USING btree (portfolio_reference);
CREATE UNIQUE INDEX rent_incentives_pkey ON public.rent_incentives USING btree (incentive_id);
CREATE UNIQUE INDEX significant_events_pkey ON public.significant_events USING btree (event_id);
CREATE UNIQUE INDEX supplier_bills_asset_id_block_name_bill_month_key ON public.supplier_bills USING btree (asset_id, block_name, bill_month);
CREATE UNIQUE INDEX supplier_bills_pkey ON public.supplier_bills USING btree (bill_id);
CREATE UNIQUE INDEX tenant_activity_pkey ON public.tenant_activity USING btree (activity_id);
CREATE UNIQUE INDEX tenants_pkey ON public.tenants USING btree (tenant_id);
CREATE UNIQUE INDEX unique_active_meter_per_unit ON public.meters USING btree (unit_id) WHERE (active = true);
CREATE UNIQUE INDEX unique_current_rate ON public.utility_rates USING btree (asset_id, block_id, utility_type, effective_to) NULLS NOT DISTINCT;
CREATE UNIQUE INDEX units_pkey ON public.units USING btree (unit_id);
CREATE UNIQUE INDEX units_unit_reference_key ON public.units USING btree (unit_reference);
CREATE UNIQUE INDEX utility_rates_pkey ON public.utility_rates USING btree (rate_id);
CREATE UNIQUE INDEX utility_rates_rate_reference_key ON public.utility_rates USING btree (rate_reference);
CREATE UNIQUE INDEX vat_config_pkey ON public.vat_config USING btree (asset_id);

-- TRIGGERS

CREATE TRIGGER trg_assets_updated_at BEFORE UPDATE ON public.assets FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_blocks_updated_at BEFORE UPDATE ON public.blocks FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_charge_profiles_updated_at BEFORE UPDATE ON public.charge_profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_charge_records_updated_at BEFORE UPDATE ON public.charge_records FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_compliance_records_updated_at BEFORE UPDATE ON public.compliance_records FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_contractors_updated_at BEFORE UPDATE ON public.contractors FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_document_templates_updated_at BEFORE UPDATE ON public.document_templates FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_documents_updated_at BEFORE UPDATE ON public.documents FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_leases_updated_at BEFORE UPDATE ON public.leases FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_maintenance_events_updated_at BEFORE UPDATE ON public.maintenance_events FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_meter_reads_updated_at BEFORE UPDATE ON public.meter_reads FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_meters_updated_at BEFORE UPDATE ON public.meters FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_portfolios_updated_at BEFORE UPDATE ON public.portfolios FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_rent_incentives_updated_at BEFORE UPDATE ON public.rent_incentives FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_significant_events_updated_at BEFORE UPDATE ON public.significant_events FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_tenants_updated_at BEFORE UPDATE ON public.tenants FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_unique_active_lease_per_unit BEFORE INSERT OR UPDATE ON public.lease_units FOR EACH ROW EXECUTE FUNCTION check_unique_active_lease_per_unit();
CREATE TRIGGER trg_units_updated_at BEFORE UPDATE ON public.units FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_utility_rates_updated_at BEFORE UPDATE ON public.utility_rates FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
